services:
  redis:
    image: redis:alpine
    networks:
      - redis
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 50M

  main:
    build: ./main_service
    networks:
      - redis
    ports:
      - 8000:8000
    volumes:
      - ./main_service/src:/app/src
      - ./db.sqlite3:/app/db.sqlite3
    command: sh -c "python manage.py makemigrations && python manage.py migrate && daphne -b 0.0.0.0 -p 8000 my_site.asgi:application"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 50M

  auth:
    build: ./auth_service
    networks:
      - redis
    ports:
      - 8001:8001
    volumes:
      - ./auth_service/src:/app/src
      - ./db.sqlite3:/app/db.sqlite3
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8001"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 50M

  info:
    build: ./info_service
    networks:
      - redis
    ports:
      - 8002:8002
    volumes:
      - ./info_service/src:/app/src
      - ./db.sqlite3:/app/db.sqlite3
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8002"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 50M


networks:
  redis:
