# Generated by Django 5.1 on 2025-05-04 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_alter_review_options_remove_review_dislikes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
