name: Deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: setup ssh
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_ed25519
        echo ${{ secrets.SSH_PRIVATE_KEY }} | base64 -d > ~/.ssh/id_ed25519
        ssh-keyscan ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
    - name: git pull
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git pull && exit"
      
